[theme]
backgroundColor = "#FFFFFF"
font = "sans serif"
primaryColor = "#F63366"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
